spring:
  application:
    name: spring2025_2_27
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis_test?
      characterEncoding=utf8&useSSL=false
    username: root
    password: woshizjy12138
    driver-class-name: com.mysql.cj.jdbc.Driver

#logging:
#  level:
#    com:
#      test:
#        spring2025_2_27:
#          Controller: info
#    root: info
#  file:
#    path: log/log.log
#  logback:
#    rollingpolicy:
#      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i
#      max-file-size: 1KB


