spring:
  application:
    name: LibraryManagement
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/book_test?characterEncoding=utf8&useSSL=false
    username: root
    password: woshizjy12138
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration: # ???? MyBatis??
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #????????
